# Triplet Loss

### Load Train, Test, and Validation data

In [2]:
import numpy as np

In [3]:
train_features_path =  "../feature/BENGALI-feature/train_features.npy"
train_names_path = "../feature/BENGALI-feature/train_names.npy"
train_labels_path = "../feature/BENGALI-feature/train_labels.npy"

test_features_path = "../feature/BENGALI-feature/test_features.npy"
test_names_path = "../feature/BENGALI-feature/test_names.npy"
test_labels_path = "../feature/BENGALI-feature/test_labels.npy"

validation_features_path = "../feature/BENGALI-feature/validation_features.npy"
validation_names_path = "../feature/BENGALI-feature/validation_names.npy"
validation_labels_path = "../feature/BENGALI-feature/validation_labels.npy"

gallery_feature_path = "../feature/BENGALI-feature/gallery_features.npy"
gallery_name_path = "../feature/BENGALI-feature/gallery_names.npy"

train_features = np.load(train_features_path)
train_names = np.load(train_names_path)
train_labels = np.load(train_labels_path)

test_features = np.load(test_features_path)
test_names = np.load(test_names_path)
test_labels = np.load(test_labels_path)

validation_features = np.load(validation_features_path)
validation_names = np.load(validation_names_path)
validation_labels = np.load(validation_labels_path)

gallery_features = np.load(gallery_feature_path)
gallery_names = np.load(gallery_name_path)

In [4]:
print(train_features.shape)
print(train_labels.shape)
print(train_names.shape)
print(test_features.shape)
print(test_labels.shape)
print(test_names.shape)
print(validation_features.shape)
print(validation_labels.shape)
print(validation_names.shape)
print(gallery_features.shape)
print(gallery_names.shape)

(3200, 512)
(3200,)
(3200,)
(1100, 512)
(1100,)
(1100,)
(1100, 512)
(1100,)
(1100,)
(100, 512)
(100,)


### Creating Triplets

In [5]:
unique_names = set(train_names.flatten())
sorted_names = sorted(unique_names)

In [6]:
print(sorted_names)

['001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025', '026', '027', '028', '029', '030', '031', '032', '033', '034', '035', '036', '037', '038', '039', '040', '041', '042', '043', '044', '045', '046', '047', '048', '049', '050', '051', '052', '053', '054', '055', '056', '057', '058', '059', '060', '061', '062', '063', '064', '065', '066', '067', '068', '069', '070', '071', '072', '073', '074', '075', '076', '077', '078', '079', '080', '081', '082', '083', '084', '085', '086', '087', '088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100']


In [7]:
print(gallery_names)

['001' '002' '003' '004' '005' '006' '007' '008' '009' '010' '011' '012'
 '013' '014' '015' '016' '017' '018' '019' '020' '021' '022' '023' '024'
 '025' '026' '027' '028' '029' '030' '031' '032' '033' '034' '035' '036'
 '037' '038' '039' '040' '041' '042' '043' '044' '045' '046' '047' '048'
 '049' '050' '051' '052' '053' '054' '055' '056' '057' '058' '059' '060'
 '061' '062' '063' '064' '065' '066' '067' '068' '069' '070' '071' '072'
 '073' '074' '075' '076' '077' '078' '079' '080' '081' '082' '083' '084'
 '085' '086' '087' '088' '089' '090' '091' '092' '093' '094' '095' '096'
 '097' '098' '099' '100']


In [85]:
def create_triplets(unique_names, gallery_features, features, labels):
    anchors, positives, negatives = [], [], []
    for name, gallery in zip(unique_names, gallery_features):
        # find all the instances for name
        indices = np.where(train_names == name)[0]
        # print(indices)
        
        # separate instances to positive and negative
        positive_set, negative_set = [], []
        for index in indices:
            # print(index)
            if labels[index] == 0:
                negative_set.append(features[index])
                # print(features[index])
            else:
                positive_set.append(features[index]) 

        negative_set = np.array(negative_set)
        positive_set = np.array(positive_set)

        # use feature gallery for anchor
        # print(gallery.size)
        anchor = gallery
        
        # print(positive_set.size)
        # print(negative_set.size)

        # randomize data picks to accomodate for unequal data size (total size is based on negative data size due to it being bigger than positive data size)
        positive_idx = np.random.choice(len(positive_set), size=len(negative_set), replace=True)
        positive = positive_set[positive_idx]
        
        anchor_set = []
        for _ in range(0, len(negative_set)):
            anchor_set.append(anchor)

        anchors.append(anchor_set)
        positives.append(positive)
        negatives.append(negative_set)
        print(len(anchors))
        print(len(positives))
        print(len(negatives))

    anchors = np.concatenate(anchors, axis=0)
    
    positives = np.concatenate(positives, axis=0)

    negatives = np.concatenate(negatives, axis=0)
    
    return anchors, positives, negatives

In [86]:
anchors, positives, negatives = create_triplets(sorted_names, gallery_features, train_features, train_labels)

1
1
1
2
2
2
3
3
3
4
4
4
5
5
5
6
6
6
7
7
7
8
8
8
9
9
9
10
10
10
11
11
11
12
12
12
13
13
13
14
14
14
15
15
15
16
16
16
17
17
17
18
18
18
19
19
19
20
20
20
21
21
21
22
22
22
23
23
23
24
24
24
25
25
25
26
26
26
27
27
27
28
28
28
29
29
29
30
30
30
31
31
31
32
32
32
33
33
33
34
34
34
35
35
35
36
36
36
37
37
37
38
38
38
39
39
39
40
40
40
41
41
41
42
42
42
43
43
43
44
44
44
45
45
45
46
46
46
47
47
47
48
48
48
49
49
49
50
50
50
51
51
51
52
52
52
53
53
53
54
54
54
55
55
55
56
56
56
57
57
57
58
58
58
59
59
59
60
60
60
61
61
61
62
62
62
63
63
63
64
64
64
65
65
65
66
66
66
67
67
67
68
68
68
69
69
69
70
70
70
71
71
71
72
72
72
73
73
73
74
74
74
75
75
75
76
76
76
77
77
77
78
78
78
79
79
79
80
80
80
81
81
81
82
82
82
83
83
83
84
84
84
85
85
85
86
86
86
87
87
87
88
88
88
89
89
89
90
90
90
91
91
91
92
92
92
93
93
93
94
94
94
95
95
95
96
96
96
97
97
97
98
98
98
99
99
99
100
100
100


In [88]:
print(len(anchors))

1800


In [89]:
triplets = []
for anchor, positive, negative in zip(anchors, positives, negatives):
    triplets.append((anchor, positive, negative))

### Triplet Loss Function

In [90]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [91]:
def create_triplet_loss_model(input_shape):
    anchor_input = layers.Input(shape=input_shape, name='anchor_input')
    positive_input = layers.Input(shape=input_shape, name='positive_input')
    negative_input = layers.Input(shape=input_shape, name='negative_input')

    # Triplet loss function
    margin = 0.2
    positive_distance = tf.reduce_sum(tf.square(anchor_input - positive_input), axis=1)
    negative_distance = tf.reduce_sum(tf.square(anchor_input - negative_input), axis=1)
    loss = tf.maximum(0.0, positive_distance - negative_distance + margin)
    loss = tf.reduce_mean(loss)

    triplet_loss_model = models.Model(inputs=[anchor_input, positive_input, negative_input], outputs=loss)
    return triplet_loss_model

In [92]:
input_shape = (train_features.shape[1],)
triplet_model = create_triplet_loss_model(input_shape)
triplet_model.compile(optimizer='adam', loss=lambda y_true, y_pred: y_pred)

In [93]:
triplet_model.summary()

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 anchor_input (InputLayer)   [(None, 512)]                0         []                            
                                                                                                  
 positive_input (InputLayer  [(None, 512)]                0         []                            
 )                                                                                                
                                                                                                  
 negative_input (InputLayer  [(None, 512)]                0         []                            
 )                                                                                                
                                                                                            

In [94]:
embedding_model = models.Sequential([
    layers.Input(shape=input_shape),
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu')
])

In [95]:
embedding_model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 512)               262656    
                                                                 
 dense_13 (Dense)            (None, 256)               131328    
                                                                 
 dense_14 (Dense)            (None, 128)               32896     
                                                                 
Total params: 426880 (1.63 MB)
Trainable params: 426880 (1.63 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [96]:
triplet_model.fit([anchors, positives, negatives], np.zeros_like(anchors), epochs=10, batch_size=32)

Epoch 1/10

57/57 [==============================] - 1s 3ms/step - loss: 3.3858
Epoch 2/10
57/57 [==============================] - 0s 3ms/step - loss: 3.3858
Epoch 3/10
57/57 [==============================] - 0s 3ms/step - loss: 3.3858
Epoch 4/10
57/57 [==============================] - 0s 2ms/step - loss: 3.3858
Epoch 5/10
57/57 [==============================] - 0s 3ms/step - loss: 3.3858
Epoch 6/10
57/57 [==============================] - 0s 3ms/step - loss: 3.3858
Epoch 7/10
57/57 [==============================] - 0s 3ms/step - loss: 3.3858
Epoch 8/10
57/57 [==============================] - 0s 2ms/step - loss: 3.3858
Epoch 9/10
57/57 [==============================] - 0s 2ms/step - loss: 3.3858
Epoch 10/10
57/57 [==============================] - 0s 2ms/step - loss: 3.3858


In [97]:
train_embeddings = embedding_model.predict(train_features)

100/100 [==============================] - 1s 4ms/step


In [98]:
print(train_embeddings)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [99]:
if np.any(train_embeddings == 1):
    print("The value 1 is present in train_embeddings.")
else:
    print("The value 1 is not present in train_embeddings.")

The value 1 is not present in train_embeddings.
